version: '3'
services:
  aspnet-react-container:
    # Uncomment the next line to use a non-root user for all processes. You can also
    # simply use the "remoteUser" property in devcontainer.json if you just want VS Code
    # and its sub-processes (terminals, tasks, debugging) to execute as the user. On Linux,
    # you may need to update USER_UID and USER_GID in .devcontainer/Dockerfile to match your
    # user if not 1000. See https://aka.ms/vscode-remote/containers/non-root for details.
    # user: vscode
    build: 
      context: .
      dockerfile: Dockerfile
    
    image: devcontainer_aspnet-react-base:dev

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/app:cached
      - node_modules:/app/src/ClientApp/node_modules/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      dev-net:
    container_name: aspnet-react-container.dev
    command: /bin/sh -c "dotnet restore && while sleep 1000; do :; done"
    environment:
      - REACT_DEV_SERVER_URI=http://react-dev-server:3000/
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5000;http://+:5001
      - REPO_ROOT_DIR=/app
    depends_on:
      - react-dev-server
    working_dir: /app/src
    ports:
      - 5000:5000
      - 5001:5001
  react-dev-server:   
    image: node:12

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../src/ClientApp:/app/src/ClientApp:cached
      - node_modules:/app/src/ClientApp/node_modules/
    networks:
      dev-net:
    container_name: react-dev-server.dev
    working_dir: /app/src/ClientApp
    command: /bin/sh -c "npm ci && npm start"
    environment:
      - NODE_ENV=development
      # necessary for to react hot module reload to pick up watched source changes done outside the docker container
      # https://github.com/paulmillr/chokidar#performance
      #- CHOKIDAR_USEPOLLING=true
      #- CHOKIDAR_INTERVAL=1000

  e2e-tests-dev:
    image: "cypress/included:4.5.0"
    depends_on:
      - aspnet-react-container
    environment:
      - CYPRESS_baseUrl=http://aspnet-react-container:5000
    container_name: e2e-tests-dev
    # "cypress/included" images have entrypoint set to globally installed cypress
    # so the command can simply add any arguments
    entrypoint: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../src/ClientApp/e2eTests:/e2eTests
      - ../e2eTestResults:/e2eTestResults
    working_dir: /e2eTests
    networks:
      dev-net:
networks:
  dev-net:
volumes:
  node_modules:



