name: Deploy on release

on:
  release:
    types: [published]

env:
  VERSION: v0.0.1

jobs:
  deploy-k3s:
    runs-on: [self-hosted, deploy, k3s]

    steps:
    - uses: actions/checkout@v2
    - name: Create secret for the github docker registry    
      run: . ./.github/workflows/deploy/createGithubRegistrySecret.sh
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        # create this secret in https://github.com/${{ github.actor }}/${{ github.repository }}/settings/secrets
        # providing PAT value with read:packages permission from: https://github.com/settings/tokens
        PAT_TOKEN: ${{ secrets.GithubDockerRegistryRead }} 
    - name: deploy to k3s
      run: sudo kubectl -f ./.github/workflows/deploy/aspnet-react-deployment.yaml apply
