# This is a basic workflow to help you get started with Actions

name: deploy

on:
  registry_package:
    types: [published]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:    
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: docker-compose up
      run: docker-compose build -f ./production/docker-compose.yaml up --detach      
      env:
        DOCKER_REPOSITORY: docker.pkg.github.com/${{ github.repository }}
        VERSION: latest